AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'

LineLength:
  Max: 100
Style/RedundantReturn:
  Enabled: false
Style/SpaceBeforeBlockBraces:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
